Corrected in Lib/mimetypes.py according to
http://bugs.python.org/review/9291/patch/191/354